name: Empty Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  empty_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: |
          echo "This does nothing"
          sleep 30
